/*
 * generated by Xtext 2.23.0
 */
package orders;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OrdersStandaloneSetup extends OrdersStandaloneSetupGenerated {

	public static void doSetup() {
		new OrdersStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
