/*
 * generated by Xtext 2.23.0
 */
package orders.parser.antlr;

import com.google.inject.Inject;
import orders.parser.antlr.internal.InternalOrdersParser;
import orders.services.OrdersGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class OrdersParser extends AbstractAntlrParser {

	@Inject
	private OrdersGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOrdersParser createParser(XtextTokenStream stream) {
		return new InternalOrdersParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ECommerce";
	}

	public OrdersGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OrdersGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
