/*
 * generated by Xtext 2.23.0
 */
package orders.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOrdersScopeProvider extends DelegatingScopeProvider {
}
