/*
 * generated by Xtext 2.23.0
 */
package orders.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OrdersUiModule extends AbstractOrdersUiModule {

	public OrdersUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
