/*
 * generated by Xtext 2.28.0
 */
package wizards.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWizardScopeProvider extends DelegatingScopeProvider {
}
