/*
 * generated by Xtext 2.23.0
 */
package orders.ui.quickfix;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.*;
import org.eclipse.xtext.ui.editor.quickfix.*;
import org.eclipse.xtext.validation.Issue;

import orders.Item;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class OrdersQuickfixProvider extends DefaultQuickfixProvider {
	
	@Fix("emptyStock")
	public void populateStock (final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, 
				"Initialize stock", 
				"Stock is set to 1", 
				"icon.png",
				// model manipulation
				(EObject element, IModificationContext context) -> { 
					((Item)element).setStock(1); 
				}				
		);
	}
	
	@Fix("emptyStock")
	public void populateStock2 (final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, 
				"Initialize stock (v2)", 
				"Stock is set to 1", 
				"icon.png",
				// text manipulation
				new IModification() {
					public void apply(IModificationContext context) throws Exception {
						IXtextDocument xtextDocument = context.getXtextDocument();
						xtextDocument.replace (
							issue.getOffset(), 
							issue.getLength(), 
							"1");
					}}
		);
	}
}
