/*
 * generated by Xtext 2.28.0
 */
package wizards.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import wizards.WizardRuntimeModule;
import wizards.WizardStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class WizardIdeSetup extends WizardStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new WizardRuntimeModule(), new WizardIdeModule()));
	}
	
}
