/*
 * generated by Xtext 2.28.0
 */
package wizards;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WizardRuntimeModule extends AbstractWizardRuntimeModule {
}
