/*
 * generated by Xtext 2.28.0
 */
package wizards;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class WizardStandaloneSetup extends WizardStandaloneSetupGenerated {

	public static void doSetup() {
		new WizardStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
