/*
 * generated by Xtext 2.23.0
 */
package orders.validation;

import org.eclipse.xtext.validation.Check;

import orders.Item;
import orders.OrdersPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class OrdersValidator extends AbstractOrdersValidator {
	
    @Check
    public void stockBiggerThan0 (Item item) {
      if (item.getStock() == 0) 
        warning("Stock is empty", 
                 OrdersPackage.Literals.ITEM__STOCK, 
                 "emptyStock");
    }
    
    @Check
    public void stockPositive (Item item) {
      if (item.getStock() < 0)
        error("Stock must be positive", 
               OrdersPackage.Literals.ITEM__STOCK, 
               "invalidStock");
    }
}