/*
 * generated by Xtext 2.23.0
 */
package orders.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import orders.OrdersRuntimeModule;
import orders.OrdersStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class OrdersIdeSetup extends OrdersStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OrdersRuntimeModule(), new OrdersIdeModule()));
	}
	
}
