/*
 * generated by Xtext 2.28.0
 */
package wizards.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import wizards.editor.ui.internal.EditorActivator;

public class WizardUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EditorActivator.getInstance().getInjector("wizards.Wizard");
	}

}
